# Electrs config # 
auth = "regtest:regtest"
daemon_rpc_addr = "host.docker.internal:8332"
daemon_p2p_addr = "host.docker.internal:8333"
db_dir = "/electrs/db"
network = "regtest"
electrum_rpc_addr = "0.0.0.0:50001"
log_filters = "INFO"
